# Generated by Django 5.1.2 on 2024-11-19 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Titel ist zu kurz (min. 1 Zeichen).')])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Inhalt ist zu kurz (min. 10 Zeichen).'), django.core.validators.MaxLengthValidator(10000, message='Inhalt ist zu lang (max. 10000 Zeichen).')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Autorname ist zu kurz (min. 2 Zeichen).')])),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(2, message='Kommentar ist zu kurz (min. 2 Zeichen).'), django.core.validators.MaxLengthValidator(1000, message='Kommentar ist zu lang (max. 1000 Zeichen)')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
            ],
        ),
    ]
